apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: proxy
        image: nginx:1.24-alpine
        ports:
        - containerPort: 80
          name: proxy
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
      - name: app
        image: mateobr0/thedaveops-app
        envFrom:
        - secretRef:
            name: app-secret
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          name: app
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
          - key: nginx.conf
            path: nginx.conf
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: demo
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: app
  selector:
    app: app
  type: NodePort

