apiVersion: apps/v1
kind: Deployment
metadata:
  name:  deployment-app
  namespace: demo
  labels:
    app:  deployment-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apps

  template:
    metadata:
      labels:
        app: apps
    spec:
      containers:
      - name:  deployment-app
        image: mateobr0/simple-vite-app