apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-name
  namespace: limitado
spec:
  hard:
    requests.cpu: '1'
    requests.memory: 1Gi
    limits.cpu: '2'
    limits.memory: 2Gi
    pods: '2'