apiVersion: v1
kind: Pod
metadata:
  namespace: demo
  name: nginx-node-affinity
spec:
  containers:
  - name: myapp
    image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: size
            #operator: NotIn
            operator: In
            values:
            - large
