apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  namespace: demo
  labels:
    app: myapp
    type: front-end
spec:
  containers:
  - name: container-1
    image: mateobr0/simple-vite-app

---

apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  namespace: demo
  labels:
    app: myapp
    type: front-end
spec:
  containers:
  - name: container-1
    image: mateobr0/simple-vite-app

---

apiVersion: v1
kind: Pod
metadata:
  name: pod-3
  namespace: demo
  labels:
    app: myapp
    type: front-end
spec:
  containers:
  - name: container-1
    image: mateobr0/simple-vite-app
