apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  namespace: demo
spec:
  containers:
  - name: webapp
    image: kodekloud/simple-webapp-mysql
    envFrom:
    - secretRef:
        name: db-secret

---

apiVersion: v1
kind: Pod
metadata:
  labels: 
    name: mysql
  name: mysql
  namespace: demo
spec:
  containers:
  - env:
    - name: MYSQL_ROOT_PASSWORD
      value: password123
    image: mysql:5.6
    name: mysql
    ports:
    - containerPort: 3306
      protocol: TCP