apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: demo
data:
  DB_Host: c3FsMDE=
  DB_User: cm9vdA==
  DB_Password: cGFzc3dvcmQxMjM=

  # Example:
  # password: {{ .Values.password | b64enc }}