apiVersion: v1
kind: Pod
metadata:
  name: web-color
  namespace: demo
spec:
  containers:
  - name: container
    image: kodekloud/webapp-color
    env:
    - name: APP_COLOR
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: APP_COLOR